### ISSUE TITLE
Extract data presence absence by data points in LetsR

### ISSUE THREAD

**Issue by philiptsoares** [BrunoVilela/letsR#5]
Hello Bruno.

Is there a function in the LetsR package that allows creating a presence and absence matrix based on points of occurrence, instead of distribution shapes?

**Comment by fabro** [comment]
Dear Philip, 

Thanks for your interest in our package. Yes, that function does exist in letsR ;) it is called: 'lets.presab.points' and it returns the same objects (within a list) as the original 'lets.presab' function.  Hope this is useful. 

Best,
Fabricio

**Comment by philiptsoares** [comment]
Hi Fabrício! 

Thanks for helping me!

I took a good look at the function and it works with the species vectors, right?
In my case, I need something that creates a matrix of presence and absence using the limits of a given shape (e.g. municipalities) and obtains the species that are located within those limits.

Thanks for attention.
Hug.

**Comment by fabro** [comment]
Hi Philip,

Yes, the function works with a vector (actually a matrix) with species names and coordinates from their point occurrences. In your case, just off the top of my head, what you could do is create the PAM for all of your species across a region and then cut that PAM using a given shape(s). For this, you could use the function "lets.pamcrop" to the object resulting from "lets.preasb.points". Alternatively, you could first select (as in any GIS) the species occurrences within a shape and then create the PAM with that species list. Instead, If what you're looking for is simply a list of species per municipality, I guess it would be simpler to use other functions such as gIntersection from rgeos package. 

Good luck!
F

**Comment by philiptsoares** [comment]
Hi Fabrício! 

Thanks for help. 
I managed to generate the matrix.
Your guidance helped a lot.

Hug.
