### ISSUE TITLE
Small error with `lets.presab.birds`

### ISSUE THREAD

**Issue by rasenior** [BrunoVilela/letsR#6]
I've just been playing around with `lets.presab.birds` and discovered that the example from the documentation:

    data(Phyllomedusa)
    PAM <- lets.presab(Phyllomedusa, xmn = -93, xmx = -29, ymn = -57, ymx = 15)

Results in:

    Error in nomes[j] <- par.re[[2]] : replacement has length zero

I investigated the code and narrowed it down to the line `nomesj <- levels(shp$SCINAME)[1]` within the auxiliary function `.extractpos.birds`. At least for my data, and for the example data, this results in `NULL`. I replaced `levels` with `unique` and it works no problem. Does that make sense as a fix? 

Thanks for the great package, very useful!

**Comment by BrunoVilela** [comment]
Hi @rasenior, thanks for reporting this issue. I've just fixed it on the github version.
